apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailslurper-deployment
  labels:
    app: mailslurper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailslurper
  template:
    metadata:
      labels:
        app: mailslurper
    spec:
      containers:
      - name: mailslurper-deployment
        image: oryd/mailslurper:latest-smtps
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4436
