hydra:
  config:
    serve:
      public:
        cors:
          enabled: true

    oidc:
      subject_identifiers:
        supported_types:
          - public
          - pairwise
        pairwise:
          salt: youReallyNeedToChangeThis

    urls:
      login: http://localhost:4485/login
      consent: http://localhost:4485/auth/consent
      logout: http://localhost:4485/logout
      error: http://localhost:4485/error
      self:
        public: http://localhost:4444/
        issuer: http://localhost:4444/

    ttl:
      access_token: 1h
      refresh_token: 1h
      id_token: 1h
      auth_code: 1h

    oauth2:
      expose_internal_errors: true

    secrets:
      cookie:
        - youReallyNeedToChangeThis
      system:
        - youReallyNeedToChangeThis

    log:
      leak_sensitive_values: true
      level: debug
    
  dev: true
