apiVersion: v1
kind: Service
metadata:
  name: go-self-service-ui-service
spec:
  selector:
   # Selector for Pods
    app: go-self-service-ui
  ports:
   # Port Map
    - port: 4485
      targetPort: 4485
      protocol: TCP
  type: ClusterIP
